[2024-04-03T17:31:28.341+0300] {taskinstance.py:1969} INFO - Dependencies not met for <TaskInstance: dag_id_3.check_table_existence scheduled__2018-11-11T00:00:00+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2024-04-03T17:31:28.343+0300] {local_task_job_runner.py:160} INFO - Task is not able to be run
