[2024-03-29T11:24:07.161+0200] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trigger_dag.trigger_dag_task manual__2024-03-29T09:21:53.301576+00:00 [queued]>
[2024-03-29T11:24:07.192+0200] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trigger_dag.trigger_dag_task manual__2024-03-29T09:21:53.301576+00:00 [queued]>
[2024-03-29T11:24:07.193+0200] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-29T11:24:07.211+0200] {taskinstance.py:2214} INFO - Executing <Task(TriggerDagRunOperator): trigger_dag_task> on 2024-03-29 09:21:53.301576+00:00
[2024-03-29T11:24:07.217+0200] {standard_task_runner.py:60} INFO - Started process 31451 to run task
[2024-03-29T11:24:07.227+0200] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'trigger_dag', 'trigger_dag_task', 'manual__2024-03-29T09:21:53.301576+00:00', '--job-id', '1204', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/var/folders/t6/vwjsg0jx26jcjdwn_gxhbjzc0000gp/T/tmpk65d7a0u']
[2024-03-29T11:24:07.230+0200] {standard_task_runner.py:88} INFO - Job 1204: Subtask trigger_dag_task
[2024-03-29T11:24:07.365+0200] {task_command.py:423} INFO - Running <TaskInstance: trigger_dag.trigger_dag_task manual__2024-03-29T09:21:53.301576+00:00 [running]> on host C9843
[2024-03-29T11:24:07.587+0200] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='trigger_dag' AIRFLOW_CTX_TASK_ID='trigger_dag_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-29T09:21:53.301576+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-29T09:21:53.301576+00:00'
[2024-03-29T11:24:07.808+0200] {trigger_dagrun.py:210} INFO - Waiting for dag_id_3 on 2024-03-29 09:24:07.590347+00:00 to become allowed state ['success'] ...
[2024-03-29T11:25:07.837+0200] {trigger_dagrun.py:210} INFO - Waiting for dag_id_3 on 2024-03-29 09:24:07.590347+00:00 to become allowed state ['success'] ...
[2024-03-29T11:26:07.914+0200] {trigger_dagrun.py:210} INFO - Waiting for dag_id_3 on 2024-03-29 09:24:07.590347+00:00 to become allowed state ['success'] ...
[2024-03-29T11:26:08.716+0200] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to queued. Terminating instance.
[2024-03-29T11:26:08.739+0200] {process_utils.py:131} INFO - Sending 15 to group 31451. PIDs of all processes in the group: [31451]
[2024-03-29T11:26:08.739+0200] {process_utils.py:86} INFO - Sending the signal 15 to group 31451
[2024-03-29T11:26:08.740+0200] {taskinstance.py:2480} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-03-29T11:26:08.758+0200] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/operators/trigger_dagrun.py", line 216, in execute
    time.sleep(self.poke_interval)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2482, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-03-29T11:26:08.765+0200] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=trigger_dag, task_id=trigger_dag_task, execution_date=20240329T092153, start_date=20240329T092407, end_date=20240329T092608
[2024-03-29T11:26:08.804+0200] {standard_task_runner.py:107} ERROR - Failed to execute job 1204 for task trigger_dag_task (Task received SIGTERM signal; 31451)
[2024-03-29T11:26:08.838+0200] {process_utils.py:79} INFO - Process psutil.Process(pid=31451, status='terminated', exitcode=1, started='11:24:07') (31451) terminated with exit code 1
