[2024-03-25T11:33:51.760+0200] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trigger_dag.wait_run_file manual__2024-03-25T09:31:58.753348+00:00 [queued]>
[2024-03-25T11:33:51.766+0200] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trigger_dag.wait_run_file manual__2024-03-25T09:31:58.753348+00:00 [queued]>
[2024-03-25T11:33:51.766+0200] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-25T11:33:51.793+0200] {taskinstance.py:2214} INFO - Executing <Task(FileSensor): wait_run_file> on 2024-03-25 09:31:58.753348+00:00
[2024-03-25T11:33:51.796+0200] {standard_task_runner.py:60} INFO - Started process 21293 to run task
[2024-03-25T11:33:51.801+0200] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'trigger_dag', 'wait_run_file', 'manual__2024-03-25T09:31:58.753348+00:00', '--job-id', '537', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/var/folders/t6/vwjsg0jx26jcjdwn_gxhbjzc0000gp/T/tmp01h7z4sd']
[2024-03-25T11:33:51.803+0200] {standard_task_runner.py:88} INFO - Job 537: Subtask wait_run_file
[2024-03-25T11:33:51.875+0200] {task_command.py:423} INFO - Running <TaskInstance: trigger_dag.wait_run_file manual__2024-03-25T09:31:58.753348+00:00 [running]> on host C9843
[2024-03-25T11:33:52.002+0200] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='trigger_dag' AIRFLOW_CTX_TASK_ID='wait_run_file' AIRFLOW_CTX_EXECUTION_DATE='2024-03-25T09:31:58.753348+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-25T09:31:58.753348+00:00'
[2024-03-25T11:33:52.013+0200] {base.py:83} INFO - Using connection ID 'fs_default' for task execution.
[2024-03-25T11:33:52.014+0200] {filesystem.py:66} INFO - Poking for file /Users/abatcoveanu/airflow/dags/subdag.py/run
[2024-03-25T11:34:52.024+0200] {base.py:83} INFO - Using connection ID 'fs_default' for task execution.
[2024-03-25T11:34:52.024+0200] {filesystem.py:66} INFO - Poking for file /Users/abatcoveanu/airflow/dags/subdag.py/run
[2024-03-25T11:35:52.050+0200] {base.py:83} INFO - Using connection ID 'fs_default' for task execution.
[2024-03-25T11:35:52.051+0200] {filesystem.py:66} INFO - Poking for file /Users/abatcoveanu/airflow/dags/subdag.py/run
[2024-03-25T11:35:52.052+0200] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/sensors/base.py", line 282, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 120.04672528500001 seconds exceeds the specified timeout of 100.0.
[2024-03-25T11:35:52.067+0200] {taskinstance.py:1149} INFO - Immediate failure requested. Marking task as FAILED. dag_id=trigger_dag, task_id=wait_run_file, execution_date=20240325T093158, start_date=20240325T093351, end_date=20240325T093552
[2024-03-25T11:35:52.096+0200] {standard_task_runner.py:107} ERROR - Failed to execute job 537 for task wait_run_file (Sensor has timed out; run duration of 120.04672528500001 seconds exceeds the specified timeout of 100.0.; 21293)
[2024-03-25T11:35:52.138+0200] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-25T11:35:52.196+0200] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
