[2024-03-28T11:10:24.531+0200] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trigger_dag.wait_run_file manual__2024-03-28T09:10:20.529208+00:00 [queued]>
[2024-03-28T11:10:24.569+0200] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trigger_dag.wait_run_file manual__2024-03-28T09:10:20.529208+00:00 [queued]>
[2024-03-28T11:10:24.569+0200] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-28T11:10:24.589+0200] {taskinstance.py:2214} INFO - Executing <Task(FileSensor): wait_run_file> on 2024-03-28 09:10:20.529208+00:00
[2024-03-28T11:10:24.594+0200] {standard_task_runner.py:60} INFO - Started process 8223 to run task
[2024-03-28T11:10:24.601+0200] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'trigger_dag', 'wait_run_file', 'manual__2024-03-28T09:10:20.529208+00:00', '--job-id', '1060', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/var/folders/t6/vwjsg0jx26jcjdwn_gxhbjzc0000gp/T/tmp2wdd7p49']
[2024-03-28T11:10:24.605+0200] {standard_task_runner.py:88} INFO - Job 1060: Subtask wait_run_file
[2024-03-28T11:10:24.767+0200] {task_command.py:423} INFO - Running <TaskInstance: trigger_dag.wait_run_file manual__2024-03-28T09:10:20.529208+00:00 [running]> on host C9843
[2024-03-28T11:10:25.030+0200] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='trigger_dag' AIRFLOW_CTX_TASK_ID='wait_run_file' AIRFLOW_CTX_EXECUTION_DATE='2024-03-28T09:10:20.529208+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-28T09:10:20.529208+00:00'
[2024-03-28T11:10:25.133+0200] {base.py:83} INFO - Using connection ID 'fs_default' for task execution.
[2024-03-28T11:10:25.135+0200] {filesystem.py:66} INFO - Poking for file /Users/abatcoveanu/airflow/dags/asd
[2024-03-28T11:11:15.237+0200] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to success. Terminating instance.
[2024-03-28T11:11:15.254+0200] {process_utils.py:131} INFO - Sending 15 to group 8223. PIDs of all processes in the group: [8223]
[2024-03-28T11:11:15.255+0200] {process_utils.py:86} INFO - Sending the signal 15 to group 8223
[2024-03-28T11:11:15.256+0200] {taskinstance.py:2480} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-03-28T11:11:15.351+0200] {process_utils.py:79} INFO - Process psutil.Process(pid=8223, status='terminated', exitcode=0, started='11:10:24') (8223) terminated with exit code 0
