[2024-03-12T10:27:49.550+0200] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: trigger_dag.wait_run_file manual__2024-03-11T10:16:01.006079+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
