[2024-03-28T10:30:08.973+0200] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trigger_dag.trigger_dag_task manual__2024-03-28T08:28:04.618700+00:00 [queued]>
[2024-03-28T10:30:09.001+0200] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trigger_dag.trigger_dag_task manual__2024-03-28T08:28:04.618700+00:00 [queued]>
[2024-03-28T10:30:09.002+0200] {taskinstance.py:2193} INFO - Starting attempt 2 of 1
[2024-03-28T10:30:09.016+0200] {taskinstance.py:2214} INFO - Executing <Task(TriggerDagRunOperator): trigger_dag_task> on 2024-03-28 08:28:04.618700+00:00
[2024-03-28T10:30:09.021+0200] {standard_task_runner.py:60} INFO - Started process 13393 to run task
[2024-03-28T10:30:09.028+0200] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'trigger_dag', 'trigger_dag_task', 'manual__2024-03-28T08:28:04.618700+00:00', '--job-id', '996', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/var/folders/t6/vwjsg0jx26jcjdwn_gxhbjzc0000gp/T/tmp4k3h0pau']
[2024-03-28T10:30:09.032+0200] {standard_task_runner.py:88} INFO - Job 996: Subtask trigger_dag_task
[2024-03-28T10:30:09.157+0200] {task_command.py:423} INFO - Running <TaskInstance: trigger_dag.trigger_dag_task manual__2024-03-28T08:28:04.618700+00:00 [running]> on host C9843
[2024-03-28T10:30:09.407+0200] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='trigger_dag' AIRFLOW_CTX_TASK_ID='trigger_dag_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-28T08:28:04.618700+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-28T08:28:04.618700+00:00'
[2024-03-28T10:30:09.620+0200] {trigger_dagrun.py:210} INFO - Waiting for dag_id_3 on 2024-03-28 08:30:09.410568+00:00 to become allowed state ['success'] ...
[2024-03-28T10:30:19.172+0200] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to success. Terminating instance.
[2024-03-28T10:30:19.189+0200] {process_utils.py:131} INFO - Sending 15 to group 13393. PIDs of all processes in the group: [13393]
[2024-03-28T10:30:19.189+0200] {process_utils.py:86} INFO - Sending the signal 15 to group 13393
[2024-03-28T10:30:19.190+0200] {taskinstance.py:2480} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-03-28T10:30:19.248+0200] {process_utils.py:79} INFO - Process psutil.Process(pid=13393, status='terminated', exitcode=0, started='10:30:09') (13393) terminated with exit code 0
