[2024-03-27T15:07:03.587+0200] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trigger_dag.process_result.sensor_triggered_dag manual__2024-03-27T13:06:07.341244+00:00 [queued]>
[2024-03-27T15:07:03.630+0200] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trigger_dag.process_result.sensor_triggered_dag manual__2024-03-27T13:06:07.341244+00:00 [queued]>
[2024-03-27T15:07:03.630+0200] {taskinstance.py:2193} INFO - Starting attempt 2 of 1
[2024-03-27T15:07:03.668+0200] {taskinstance.py:2214} INFO - Executing <Task(ExternalTaskSensor): process_result.sensor_triggered_dag> on 2024-03-27 13:06:07.341244+00:00
[2024-03-27T15:07:03.675+0200] {standard_task_runner.py:60} INFO - Started process 34538 to run task
[2024-03-27T15:07:03.685+0200] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'trigger_dag', 'process_result.sensor_triggered_dag', 'manual__2024-03-27T13:06:07.341244+00:00', '--job-id', '654', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/var/folders/t6/vwjsg0jx26jcjdwn_gxhbjzc0000gp/T/tmp92tsdmin']
[2024-03-27T15:07:03.690+0200] {standard_task_runner.py:88} INFO - Job 654: Subtask process_result.sensor_triggered_dag
[2024-03-27T15:07:13.866+0200] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-03-27T15:07:13.889+0200] {process_utils.py:131} INFO - Sending 15 to group 34538. PIDs of all processes in the group: [34538]
[2024-03-27T15:07:13.890+0200] {process_utils.py:86} INFO - Sending the signal 15 to group 34538
[2024-03-27T15:07:13.945+0200] {process_utils.py:79} INFO - Process psutil.Process(pid=34538, status='terminated', exitcode=0, started='15:07:03') (34538) terminated with exit code 0
