[2024-03-26T15:28:45.267+0200] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trigger_dag.wait_run_file manual__2024-03-26T13:28:25.970540+00:00 [queued]>
[2024-03-26T15:28:45.275+0200] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trigger_dag.wait_run_file manual__2024-03-26T13:28:25.970540+00:00 [queued]>
[2024-03-26T15:28:45.276+0200] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-26T15:28:45.289+0200] {taskinstance.py:2214} INFO - Executing <Task(FileSensor): wait_run_file> on 2024-03-26 13:28:25.970540+00:00
[2024-03-26T15:28:45.293+0200] {standard_task_runner.py:60} INFO - Started process 20538 to run task
[2024-03-26T15:28:45.300+0200] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'trigger_dag', 'wait_run_file', 'manual__2024-03-26T13:28:25.970540+00:00', '--job-id', '582', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/var/folders/t6/vwjsg0jx26jcjdwn_gxhbjzc0000gp/T/tmp0uvwply3']
[2024-03-26T15:28:45.303+0200] {standard_task_runner.py:88} INFO - Job 582: Subtask wait_run_file
[2024-03-26T15:28:45.389+0200] {task_command.py:423} INFO - Running <TaskInstance: trigger_dag.wait_run_file manual__2024-03-26T13:28:25.970540+00:00 [running]> on host C9843
[2024-03-26T15:28:45.531+0200] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='trigger_dag' AIRFLOW_CTX_TASK_ID='wait_run_file' AIRFLOW_CTX_EXECUTION_DATE='2024-03-26T13:28:25.970540+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-26T13:28:25.970540+00:00'
[2024-03-26T15:28:45.560+0200] {base.py:83} INFO - Using connection ID 'fs_default' for task execution.
[2024-03-26T15:28:45.561+0200] {filesystem.py:66} INFO - Poking for file /Users/abatcoveanu/airflow/dags/asd
[2024-03-26T15:29:45.569+0200] {base.py:83} INFO - Using connection ID 'fs_default' for task execution.
[2024-03-26T15:29:45.570+0200] {filesystem.py:66} INFO - Poking for file /Users/abatcoveanu/airflow/dags/asd
[2024-03-26T15:30:45.580+0200] {base.py:83} INFO - Using connection ID 'fs_default' for task execution.
[2024-03-26T15:30:45.582+0200] {filesystem.py:66} INFO - Poking for file /Users/abatcoveanu/airflow/dags/asd
[2024-03-26T15:30:45.583+0200] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/sensors/base.py", line 282, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 120.047450004 seconds exceeds the specified timeout of 100.0.
[2024-03-26T15:30:45.611+0200] {taskinstance.py:1149} INFO - Immediate failure requested. Marking task as FAILED. dag_id=trigger_dag, task_id=wait_run_file, execution_date=20240326T132825, start_date=20240326T132845, end_date=20240326T133045
[2024-03-26T15:30:45.622+0200] {standard_task_runner.py:107} ERROR - Failed to execute job 582 for task wait_run_file (Sensor has timed out; run duration of 120.047450004 seconds exceeds the specified timeout of 100.0.; 20538)
[2024-03-26T15:30:45.660+0200] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-26T15:30:45.709+0200] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
