[2024-04-03T17:31:37.185+0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trigger_dag.trigger_dag_task manual__2024-04-03T14:08:09.832156+00:00 [queued]>
[2024-04-03T17:31:37.216+0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trigger_dag.trigger_dag_task manual__2024-04-03T14:08:09.832156+00:00 [queued]>
[2024-04-03T17:31:37.216+0300] {taskinstance.py:2193} INFO - Starting attempt 2 of 1
[2024-04-03T17:31:37.236+0300] {taskinstance.py:2214} INFO - Executing <Task(TriggerDagRunOperator): trigger_dag_task> on 2024-04-03 14:08:09.832156+00:00
[2024-04-03T17:31:37.243+0300] {standard_task_runner.py:60} INFO - Started process 40163 to run task
[2024-04-03T17:31:37.253+0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'trigger_dag', 'trigger_dag_task', 'manual__2024-04-03T14:08:09.832156+00:00', '--job-id', '1499', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/var/folders/t6/vwjsg0jx26jcjdwn_gxhbjzc0000gp/T/tmphc77s6up']
[2024-04-03T17:31:37.255+0300] {standard_task_runner.py:88} INFO - Job 1499: Subtask trigger_dag_task
[2024-04-03T17:31:47.390+0300] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-04-03T17:31:47.409+0300] {process_utils.py:131} INFO - Sending 15 to group 40163. PIDs of all processes in the group: [40163]
[2024-04-03T17:31:47.409+0300] {process_utils.py:86} INFO - Sending the signal 15 to group 40163
[2024-04-03T17:31:47.464+0300] {process_utils.py:79} INFO - Process psutil.Process(pid=40163, status='terminated', exitcode=0, started='17:31:37') (40163) terminated with exit code 0
