[2024-04-04T11:45:18.702+0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trigger_dag.wait_run_file manual__2024-04-04T08:45:14.745168+00:00 [queued]>
[2024-04-04T11:45:18.759+0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trigger_dag.wait_run_file manual__2024-04-04T08:45:14.745168+00:00 [queued]>
[2024-04-04T11:45:18.759+0300] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-04T11:45:18.844+0300] {taskinstance.py:2214} INFO - Executing <Task(FileSensor): wait_run_file> on 2024-04-04 08:45:14.745168+00:00
[2024-04-04T11:45:18.863+0300] {standard_task_runner.py:60} INFO - Started process 40476 to run task
[2024-04-04T11:45:18.869+0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'trigger_dag', 'wait_run_file', 'manual__2024-04-04T08:45:14.745168+00:00', '--job-id', '1727', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/var/folders/t6/vwjsg0jx26jcjdwn_gxhbjzc0000gp/T/tmp99i_q4ml']
[2024-04-04T11:45:18.872+0300] {standard_task_runner.py:88} INFO - Job 1727: Subtask wait_run_file
[2024-04-04T11:45:18.991+0300] {task_command.py:423} INFO - Running <TaskInstance: trigger_dag.wait_run_file manual__2024-04-04T08:45:14.745168+00:00 [running]> on host C9843
[2024-04-04T11:45:19.209+0300] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='trigger_dag' AIRFLOW_CTX_TASK_ID='wait_run_file' AIRFLOW_CTX_EXECUTION_DATE='2024-04-04T08:45:14.745168+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-04T08:45:14.745168+00:00'
[2024-04-04T11:45:19.238+0300] {base.py:83} INFO - Using connection ID 'fs_default' for task execution.
[2024-04-04T11:45:19.239+0300] {filesystem.py:66} INFO - Poking for file /Users/abatcoveanu/airflow/dags/asd
[2024-04-04T11:46:14.501+0300] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to success. Terminating instance.
[2024-04-04T11:46:14.512+0300] {process_utils.py:131} INFO - Sending 15 to group 40476. PIDs of all processes in the group: [40476]
[2024-04-04T11:46:14.512+0300] {process_utils.py:86} INFO - Sending the signal 15 to group 40476
[2024-04-04T11:46:14.513+0300] {taskinstance.py:2480} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-04-04T11:46:14.568+0300] {process_utils.py:79} INFO - Process psutil.Process(pid=40476, status='terminated', exitcode=0, started='11:45:18') (40476) terminated with exit code 0
